### ISSUE TITLE
Example with multiple parameters

### ISSUE THREAD

**Issue by mph911** [r1pper/Topshelf.StartParameters#1]
@r1pper: I tried to work with multiple parameters, i.e. 
`myservice -i 5 -u "xyz"`

defined it within the TopShelf constructor

```
x.WithCustomStartParameter ("pl", "name",
         a =>
         {
             if (string.IsNullOrWhiteSpace (a))
                 throw new ArgumentException ("ERROR: ...");

             int plId;
             string name;

             if (int.TryParse (a, out plId))
                 system.ProductionLineId = plId;
             else
             {
                 if (!string.IsNullOrWhiteSpace (name))
                     system.UserName = name;
                 else
                     throw new ArgumentException ("ERROR: ...");
         }
```

But it seems that I misunderstand the usage. "pl" should refer to the first and "name" to the second parameter. I also assumed that the lambda is called for each parameter found.

Please let me know if that is a correct approach or if there is a better one!

Thank you!

**Comment by r1pper** [comment]
in the above snippet, `pl` refers to the parameter name during installation and `name"` refers to it during run-time, hence when you want to run the service directly (e.g. using start command) you should call it with `name` and during installation (install command) you should call `pl`.

for multiple parameters with different names, you should call `WithCustomStartParamter` or `WithStartParamter` and define an action for each of them.

for `myservice -i 5 -u "xyz"` it can be like

## **Based on WithStartParameter**

``` c#
x.WithStartParameter ("i",a=>{ ... }); //i name can be used during installation, tsspi is generated as run-time name
x.WithStartParameter ("u",a=>{ ... }); //u name can be used during installation, tsspu is generated as run-time name
```

**Direct usage**
`myservice -tsspi "5" -tsspu "xyz"`

**Installation usage**
`myservice install  -i "5" -u "xyz"`

## **Based on WithCustomStartParameter**

``` c#
x.WithCustomStartParameter ("ci","i",a=>{ ... }); 
x.WithStartParameter ("cu","u",a=>{ ... }); 
```

**Direct usage**
`myservice -i "5" -u "xyz"`

**Installation usage**
`myservice install  -ci "5" -cu "xyz"`

## Explanation:

At first it seems that naming a same parameter twice is nonsense. but it is required because under the hood, what install command does is to set defined parameters during installation in specific registry key for Windows Service, when Windows service starts it works exactly the same as if we passed the arguments by hand. in this example `pl` is actually setting `name` in registry. albeit if you don't need to run the command manually you can only pass `pl` part and the extension will automatically create run-time name for it.

**Comment by mph911** [comment]
I completly missed the point that for every parameter a lambda is needed. Thank you very much for your almost instant answer!
Much appreachiated! :+1:
